services:
  dashboard:
    build:
      context: .
      dockerfile: src/streamlit-dash/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"